"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { apiFetch } from "../../../lib/api";
import type { ApiResponse } from "../../../shared/types/api";

type Product={id:number;name:string;brand:string;model_number:string|null;sku:string;description:string|null;selling_price:string;stock_quantity:number;image:string|null;category_id:number;is_active:boolean};
type Category={id:number;name:string;description:string|null};
export function StoreProducts(){const [products,setProducts]=useState<Product[]>([]),[cats,setCats]=useState<Category[]>([]),[category,setCategory]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");useEffect(()=>{Promise.all([apiFetch<ApiResponse<Product[]>>("/store/products"),apiFetch<ApiResponse<Category[]>>("/store/categories")]).then(([p,c])=>{setProducts(p.data);setCats(c.data)}).catch(e=>setError(e.message)).finally(()=>setLoading(false))},[]);const visible=category?products.filter(p=>String(p.category_id)===category):products;return <main className="mx-auto max-w-7xl px-6 py-10"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-3xl font-bold">Products</h1><p className="mt-1 text-slate-500">Browse products available through the online store.</p></div><select value={category} onChange={e=>setCategory(e.target.value)} className="rounded-lg border px-3 py-2 text-sm"><option value="">All categories</option>{cats.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></div>{error&&<p className="mt-6 rounded-lg bg-red-50 p-4 text-red-700">{error}</p>}{loading?<p className="mt-8">Loading products...</p>:<div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{visible.map(p=><Link key={p.id} href={`/products/${p.id}`} className="rounded-xl border bg-white p-5 transition hover:-translate-y-0.5 hover:shadow"><div className="aspect-square rounded-lg bg-slate-100"/><h2 className="mt-4 font-semibold">{p.name}</h2><p className="text-sm text-slate-500">{p.brand} · {p.sku}</p><p className="mt-3 font-bold">Rs. {p.selling_price}</p><p className="mt-1 text-xs text-slate-500">{p.stock_quantity>0?`${p.stock_quantity} in stock`:"Out of stock"}</p></Link>)}</div>}</main>}
